"""
Bundle Command Implementation

Generates Databricks Asset Bundle resource files for SchemaX deployments.
Outputs a resource YAML and a deploy script that can be included in an
existing DAB project.
"""

from __future__ import annotations

import textwrap
from pathlib import Path
from typing import Any

from schemax.core.storage import read_project
from schemax.version import SCHEMAX_VERSION

_DEPLOY_SCRIPT_TEMPLATE = textwrap.dedent("""\
    \"\"\"SchemaX deploy script for Databricks Asset Bundles.

    This script is executed as a serverless Python task by a DAB job.
    It runs `schemax apply` against the target environment using
    Databricks-native authentication (automatically provided by the job runtime).

    Generated by schemax bundle v{schemax_version}.
    \"\"\"

    import os
    import subprocess
    import sys


    def main() -> None:
        environment = os.environ.get("SCHEMAX_ENVIRONMENT", "dev")
        warehouse_id = os.environ.get("SCHEMAX_WAREHOUSE_ID", "")
        workspace_dir = os.environ.get("SCHEMAX_WORKSPACE_DIR", ".")
        auto_rollback = os.environ.get("SCHEMAX_AUTO_ROLLBACK", "false").lower() == "true"

        if not warehouse_id:
            print("ERROR: SCHEMAX_WAREHOUSE_ID environment variable is required")
            sys.exit(1)

        profile = os.environ.get("SCHEMAX_PROFILE", "")

        cmd = [
            sys.executable, "-m", "schemax",
            "apply",
            "--target", environment,
            "--profile", profile if profile else "DEFAULT",
            "--warehouse-id", warehouse_id,
            "--no-interaction",
        ]

        if auto_rollback:
            cmd.append("--auto-rollback")

        print(f"Running SchemaX apply: environment={{environment}}, warehouse={{warehouse_id}}")
        result = subprocess.run(cmd, cwd=workspace_dir)
        sys.exit(result.returncode)


    if __name__ == "__main__":
        main()
""")


def _build_resource_yaml(
    *,
    project_name: str,
    environments: dict[str, Any],
    schemax_version: str,
) -> str:
    """Build the DAB resource YAML content for SchemaX deployment."""
    lines = [
        f"# SchemaX DAB resources - generated by schemax bundle v{schemax_version}",
        "#",
        "# Include this file in your databricks.yml:",
        "#   include:",
        "#     - resources/schemax.yml",
        "#",
        "# Required variables in your databricks.yml targets:",
        "#   targets:",
        "#     dev:",
        "#       variables:",
        "#         warehouse_id: <your-sql-warehouse-id>",
        "#",
        "# The job uses ${bundle.target} as the SchemaX environment name,",
        "# so DAB target names should match your SchemaX environments",
        f"# ({', '.join(sorted(environments.keys()))}).",
        "#",
        "# Sync .schemax/ to the workspace by adding to your databricks.yml:",
        "#   sync:",
        "#     include:",
        "#       - .schemax/**",
        "#       - resources/schemax_deploy.py",
        "",
        "variables:",
        "  warehouse_id:",
        '    description: "SQL warehouse ID for SchemaX deployments"',
        "  schemax_auto_rollback:",
        '    description: "Auto-rollback on failure (true/false)"',
        '    default: "false"',
        "",
        "resources:",
        "  jobs:",
        f"    schemax_deploy_{project_name}:",
        f'      name: "schemax-deploy-{project_name}-${{bundle.target}}"',
        "      environments:",
        "        - environment_key: schemax",
        "          spec:",
        "            dependencies:",
        f"              - schemaxpy>={schemax_version}",
        "      tasks:",
        "        - task_key: schemax_apply",
        "          environment_key: schemax",
        "          spark_python_task:",
        "            python_file: resources/schemax_deploy.py",
        "          environment_variables:",
        '            SCHEMAX_ENVIRONMENT: "${bundle.target}"',
        '            SCHEMAX_WAREHOUSE_ID: "${var.warehouse_id}"',
        '            SCHEMAX_AUTO_ROLLBACK: "${var.schemax_auto_rollback}"',
    ]
    return "\n".join(lines) + "\n"


def generate_bundle(
    *,
    workspace: Path,
    output_dir: Path,
) -> dict[str, Any]:
    """Generate DAB resource files for SchemaX deployment.

    Creates:
      - <output_dir>/schemax.yml       - DAB resource fragment
      - <output_dir>/schemax_deploy.py  - Python deploy script

    Returns a summary dict with paths and metadata.
    """
    project = read_project(workspace)
    project_name: str = project.get("name", "schemax")
    provider_config = project.get("provider", {})
    environments: dict[str, Any] = provider_config.get("environments", {})

    if not environments:
        raise ValueError(
            "No environments configured in project.json. "
            "Run `schemax init` and configure environments first."
        )

    # Sanitize project name for use in YAML identifiers
    safe_name = project_name.replace("-", "_").replace(" ", "_").lower()

    output_dir.mkdir(parents=True, exist_ok=True)

    # Generate resource YAML
    resource_yaml = _build_resource_yaml(
        project_name=safe_name,
        environments=environments,
        schemax_version=SCHEMAX_VERSION,
    )
    resource_path = output_dir / "schemax.yml"
    resource_path.write_text(resource_yaml)

    # Generate deploy script
    deploy_script = _DEPLOY_SCRIPT_TEMPLATE.format(schemax_version=SCHEMAX_VERSION)
    deploy_path = output_dir / "schemax_deploy.py"
    deploy_path.write_text(deploy_script)

    return {
        "project_name": project_name,
        "environments": list(environments.keys()),
        "resource_file": str(resource_path),
        "deploy_script": str(deploy_path),
        "schemax_version": SCHEMAX_VERSION,
    }
